### ISSUE TITLE
Small FYI: New Bincrafters repository

### ISSUE THREAD

**Issue by Croydon** [iceshard-engine/conan-config#2]
I stumbled over this by accident and as a small _for your information_, regarding the readme:

> Bincrafters (https : //api.bintray.com/conan/bincrafters/public-conan) - this repository does not exist anymore.

We have a new remote at 

> https://bincrafters.jfrog.io/artifactory/api/conan/public-conan

Also see https://bincrafters.github.io/2020/04/19/infrastructure-changes-and-required-actions/

Feel free to close this after reading 🙂

**Comment by Dandielo** [comment]
Thanks for the information!

I've not used bincrafters for some time, however this might help me in the future.
